# Generated by Django 2.2.4 on 2019-09-25 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190924_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['-position']},
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='priority',
            new_name='position',
        ),
    ]
